language: ruby
sudo: false
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
install:
  - bundle install --retry=3
env:
  - RAILS_ENV=test
script:
  - bundle exec rails db:schema:load
  - bundle exec rails test
