---
- amazon
- bitbucket
- dropbox
- facebook
- flickr
- github
- google
- instagram
- linkedin
- netflix
- paypal
- skype
- soundcloud
- spotify
- stack-overflow
- steam
- tumblr
- twitch
- vimeo
- xing
- youtube
